export enum SunatErrorCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  VALIDATION = 'VALIDATION',
  DUPLICATE = 'DUPLICATE',
  TEMPORARY = 'TEMPORARY',
  REJECTED = 'REJECTED',
  UNKNOWN = 'UNKNOWN',
}
